### ISSUE TITLE
There is no iterator in Hashtable. Am I missed something?

### ISSUE THREAD

**Issue by VijitCoder** [braydenanderson2014/ArduinoHashtable#3]
From the documentation example:

```c++
    // Iterate through the keys
    Hashtable<int, String>::HashtableIterator it = dictionary.keys();
    while (it.hasNext()) {
         ...
    }
```

But I got an error:
> class "Hashtable<int, String, KeyHash<int>>" has no member "HashtableIterator"

And I don't see this class in the current repo. Why?

**Comment by braydenanderson2014** [comment]
The iterator class is nested inside the Hashtable class. And it's just called Iterator. So that's likely your problem.

**Comment by VijitCoder** [comment]
Oh, I see. Wrong documentation. Thx.

**Comment by braydenanderson2014** [comment]
I apologize, a while back I had to change the iterator class name due to weird glitches, I must of forgot to update the documentation. I will be sure to update that shortly. 

Thank you for bringing this to my attention!

-Brayden
